topic_camera_info: "/dope/gauge/camera_info"
topic_image: "/dope/gauge/image_raw"
image_dir: "/media/DOPE/MultiCarPose_v0.9/eval"
image_output_dir: "/media/DOPE/MultiCarPose_v0.9/output_eval"
graph: "package://dope/weights/car.pth"
camera_info_url : "package://dope/config/camera_info_gauge.yaml"
